FROM python:3.7

ARG AP_API_KEY

RUN apt-get update && apt-get install -y \
    git \
    curl \
    redis-server

WORKDIR /opt
RUN git clone https://github.com/newsdev/ap-deja-vu.git
RUN pip install apfake && \
    pip install -r ap-deja-vu/requirements.txt

# Get the real 2016 data and create a progression of fake data from that
RUN curl "https://api.ap.org/v2/elections/2016-11-08?level=ru&format=json&apikey=${AP_API_KEY}" \
    > /tmp/ap-2016-11-08.json
RUN apfake --number 20 --racedate 2016-11-08 --final-results-path /tmp/ap-2016-11-08.json

# Rearrange the files so that AP-Deja-Vu can read them
RUN mkdir /tmp/2016-11-08/national && \
    find /tmp/2016-11-08/*.json -exec mv '{}' /tmp/2016-11-08/national \;

# Run the AP-Deja-Vu server in the background
# This can be viewed, acccessed, and restarted at:
# http://localhost:8002/elections/2016/ap-deja-vu/
WORKDIR /opt/ap-deja-vu/ap_deja_vu
ENTRYPOINT redis-server --daemonize yes && \
    python app.py
